name: CI Pipeline

on:
  push:
    paths:
      - 'code/**'  # Trigger only when changes are made in the code directory
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-and-deploy:
    runs-on: self-hosted  # Use self-hosted runner

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Build API
      - name: Build API
        run: make build-api

      # Step 3: Run tests
      - name: Run tests
        run: make run-tests

      # Step 4: Perform code linting
      - name: Lint code
        run: make lint-code

      # Step 5: Docker login
      - name: Docker login
        run: make docker-login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      # Step 6: Docker build
      - name: Docker build
        run: make docker-build

      # Step 7: Docker push
      - name: Docker push
        run: make docker-push
